#!/usr/bin/env bash
# Install nginx on your web-01 server
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request (requesting a page) using curl,
#  .it must return a page that contains the string Hello World!

# Install nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Start server
sudo service nginx start
# allow nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Backup default index
sudo cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# root display msg
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'

# Redirect
redirect_rule="return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4"
old="server_name _;"
new="\n\n\tlocation /redirect_me {\n\t\t$redirect_rule;\n\t}"

sudo sed -i  "/$old/a \ $new" /etc/nginx/sites-available/default

# Restarting server
sudo service nginx restart
